CREATE TABLE `TASKS` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TITLE` TEXT NULL,
	`DESCRIPTION` TEXT NULL,
	`STATUS` INT(11) NULL DEFAULT NULL,
	`DATE` TEXT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1210
;